cli:
  baseUrl: https://tldr.one/
  coloredOutput: true
  home: news
  debug: false
  download: ''
  offline: false
  queryParameters:
    limit: 500
    excludeFooter: false
    sort: 'popular'
    order: 'desc'
